In [1]:
def get_tree_percent(x):
    return x['geometry_tree'].intersection(x['geometry']).area/x['geometry'].area
#tract_taz['tract_pct'] = tract_taz[['geometry','geometry_taz']].apply(get_percent, axis = 1)


In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
import os
import gdal
import rasterio

In [2]:
boundaryDir = r'data\boundaries'
treeDir = r'data\trees'

In [9]:
muni = gpd.read_file(os.path.join(boundaryDir,'MUNICIPAL_BOUNDARIES.shp'))

In [10]:
delmar = gpd.read_file(os.path.join(boundaryDir,"DEL_MAR.shp"))
#parcel = gpd.read_file(os.path.join(boundaryDir,'PARCELS.shp'))
#tracts = gpd.read_file(os.path.join(boundaryDir,'CENSUS_TRACTS_2010.shp'))
#muni = gpd.read_file(os.path.join(boundaryDir,'MUNICIPAL_BOUNDARIES.shp'))

In [11]:
landuse = gpd.read_file(os.path.join(boundaryDir,'LAND_USE_2013.shp'))


In [11]:
dmtrees = gpd.read_file(os.path.join(treeDir,'delmar_trees.shp'))

## Process Raster Data

In [4]:
# rasterio.open??
dmt = rasterio.open(os.path.join('data','images','delMar_2014_georeferenced.png'), crs = 'epsg:4326')

In [16]:
dmt.read(1)

array([[ 50,  59,  61, ...,  99, 100, 100],
       [ 54,  58,  59, ..., 109, 112, 112],
       [ 56,  58,  55, ..., 113, 115, 115],
       ...,
       [ 63,  66,  65, ...,  58,  52,  52],
       [ 67,  68,  66, ...,  54,  49,  49],
       [ 68,  68,  65, ...,  51,  50,  50]], dtype=uint8)

In [6]:
dmt.bounds

BoundingBox(left=-117.31494535559315, bottom=32.93595901336535, right=-117.21534485643745, top=32.98299379215335)

In [7]:
dmt.shape


(1080, 2287)

In [8]:
red = dmt.read(1)

In [9]:
red

array([[ 50,  59,  61, ...,  99, 100, 100],
       [ 54,  58,  59, ..., 109, 112, 112],
       [ 56,  58,  55, ..., 113, 115, 115],
       ...,
       [ 63,  66,  65, ...,  58,  52,  52],
       [ 67,  68,  66, ...,  54,  49,  49],
       [ 68,  68,  65, ...,  51,  50,  50]], dtype=uint8)

In [36]:
green = dmt.read(2)

In [37]:
blue = dmt.read(3)


In [39]:
dmt.lnglat()

CRSError: CRS is invalid: None

In [14]:
dmt.crs# = rasterio.crs.CRS.from_epsg(4326)


CRS.from_dict(init='epsg:3857')

In [28]:
green[1040]

array([256, 256, 256, ..., 256, 256, 256], dtype=uint16)

In [16]:
delmar = delmar.to_crs({'init':'epsg:3857'})

In [17]:
dmt[dmt.intersects(delmar.unary_union)]

AttributeError: 'DatasetReader' object has no attribute 'intersects'